<a href="https://colab.research.google.com/github/ClaFlorez/travaux-avril-2024/blob/main/demo_tenserflow1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

pour commencer un projet on doit toujours importer les librairies au debut du programme.

In [49]:
import tensorflow as tf

In [ ]:
!pip list

In [5]:
import tensorflow as tf

In [6]:
import os

## les ***constants***

In [7]:
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'

In [12]:
a = tf.constant(10.)

In [9]:
b = tf.constant(10.)

In [13]:
print(a + b)

tf.Tensor(20.0, shape=(), dtype=float32)


In [18]:
print("a+b=",a+b)

a+b= tf.Tensor(20.0, shape=(), dtype=float32)


In [19]:
print(f"a + b = {a+b}")

a + b = 20.0


In [22]:
!python --version

Python 3.10.12


In [29]:
c = tf.constant(5.)

In [25]:
d = tf.constant(3.)

In [30]:
print(f"{c+d}")

8.0


In [39]:
e = tf.constant (10., dtype="float32")

In [ ]:
print("Type de données de 'c'",c.dtype)

In [46]:
b= tf.constant(10.)

In [41]:
c = tf.constant(6.,dtype="float64")

In [47]:
print(f"b+c={b + tf.cast(c,tf.float32)}")

b+c=16.0


## les *matrices* **texte en gras**

In [50]:
tensor_3 = tf.zeros((3,3))

\n va a la ligne
les matrices utilisées pour les images

In [51]:
print(f"tensor_3= \n {tensor_3}")

tensor_3= 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [54]:
tensor_4 = tf.random.uniform((3,3), minval=1, maxval=10)
print(tensor_4)

tf.Tensor(
[[9.127079  1.4613249 1.626844 ]
 [7.2382154 8.147429  2.305298 ]
 [8.13633   2.3915172 8.02589  ]], shape=(3, 3), dtype=float32)


si on utilise le seed il va a redonner les memes numeros a chaque fois sans changements le numero dos entre les parenteses peut etre 2 o 200 ca ne change pas le resultat.

In [59]:
tensor_5 = tf.random.uniform((3,3),seed=2)

In [67]:
print(tensor_5)

tf.Tensor(
[[0.20001888 0.26219416 0.3048637 ]
 [0.07888281 0.17218232 0.42112756]
 [0.06079972 0.8920913  0.95070934]], shape=(3, 3), dtype=float32)


uniforme nous donnent des numeros dans tout les intervale 0 to 10.
si j'ai met random.normal les valeurs vont se raprocher de la moyenne.

In [70]:
tensor_5 = tf.random.uniform((3,3))
print(tensor_5)

tf.Tensor(
[[0.7769531  0.80698    0.40254605]
 [0.15380538 0.92538905 0.3702669 ]
 [0.54998744 0.65166616 0.5970155 ]], shape=(3, 3), dtype=float32)


matrice aleatoire a partir de un distribution normale. la deviacion standar sert dans cette exemple a definir l'écart entre les numéros.

In [79]:
tensor_normal = tf.random.normal((3,3), mean=0,stddev=-0.01)

SyntaxError: invalid syntax (<ipython-input-81-0a72cb870a75>, line 1)

In [80]:
print(tensor_normal.numpy)

<bound method _EagerTensorBase.numpy of <tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 0.00669857,  0.0100002 ,  0.02178284],
       [-0.00021404, -0.00889771, -0.00018575],
       [-0.00051359, -0.01818542, -0.00785931]], dtype=float32)>>


creer un tensor aleatoire de forme (5,3) avec des valeurs aléatoires uniformes
creer un tensor aleatoire de forme (8,8) avec des valeurs aléatoires normales et un deviation standard de 20 c'est quoi la signification de deviation standar de 20 (l'écar entres les numeros sera du 20+-

fixer le seed pour obtenir des résultats reproductibles
generer un matrice de 5 par 3 des nombres pseudo-aléatoires
et afficher la matrice

In [83]:
tensor_6 = tf.random.uniform((5,3))
print(tensor_6)

tf.Tensor(
[[0.78153276 0.13843513 0.6529114 ]
 [0.39121962 0.7739854  0.7160367 ]
 [0.6502892  0.12822747 0.06041157]
 [0.93956435 0.30949688 0.6315217 ]
 [0.44683647 0.02310276 0.79246676]], shape=(5, 3), dtype=float32)


In [84]:
tensor_7 = tf.random.normal((8,8), mean=0,stddev=20)
print(tensor_7)

tf.Tensor(
[[-13.482616   -37.52448    -42.228058    24.790646    -5.8360014
   -2.0520225    0.09939747   9.5508585 ]
 [ 11.34458     19.70322      2.224924     2.8685093  -21.704676
  -13.860823   -15.662207     5.3980355 ]
 [-44.720074     8.818017   -34.477753    10.462172   -13.692664
   16.892365    17.393822    -4.148616  ]
 [ -3.96588     19.213903   -16.751095   -39.71595     14.001536
  -29.613169    21.769915    -5.3740234 ]
 [ 18.393087   -15.807592   -13.36958      1.3512777   49.319134
   33.34689     -9.875917    -2.713351  ]
 [-19.561596    -8.519082   -36.49174    -23.856586    -9.266206
   30.704088     2.2433991   -4.973126  ]
 [ 12.044069     0.31407964  -6.13361    -19.039904    -9.767159
    7.371212   -11.788825     5.7976246 ]
 [-23.029593    -1.7573977   19.113598    -3.4222589    3.1057155
   -1.1966145   -1.8123202   -2.9984114 ]], shape=(8, 8), dtype=float32)


afficher la version de tensorflow

In [85]:
print(tf.__version__)

2.15.0


In [86]:
import numpy as np

numpy est seulement 2D pour la creation ou affichage de la instruction.
par contre tensorflow peut être 3D et plus.

In [87]:
tensor = np.random.rand(5,3)
print(tensor)

[[0.0842622  0.41326311 0.68584094]
 [0.83577496 0.90978569 0.48790718]
 [0.32157947 0.83673915 0.95786594]
 [0.1525587  0.42684888 0.28897845]
 [0.69362493 0.15741182 0.35074472]]


la demo suivante avec affichage numpy

In [88]:
tensor_7 = tf.random.normal((8,8), mean=0,stddev=20)
print(tensor_7.numpy())

[[ 10.06111      6.384692    -2.4877424    9.179088   -10.611158
  -17.218193   -25.179369    13.634741  ]
 [ 36.964687    20.24382     -7.192228     5.320204   -15.875545
   28.152678    10.877863   -22.5529    ]
 [ 27.827337   -33.529797    15.134138    13.356546   -19.865019
   43.22406    -24.685614    28.187525  ]
 [-31.351357    34.755333    -6.4586706  -17.861841    14.407665
    1.063653    -1.4248021    9.457888  ]
 [ 20.198341    26.866581   -18.242655    31.012535    -9.771815
    2.1146438    3.7588918  -19.688965  ]
 [ 27.85273    -37.203094    12.505408     3.7770538  -11.11123
   22.392962    17.604965    -7.313822  ]
 [ 10.09618    -22.607431    42.788826    31.621284   -42.895218
   -7.5412917   -3.6353576  -11.666783  ]
 [ 41.16203     25.84817      3.5179849   -0.48393333 -24.693563
  -19.534237     7.7043686   15.010294  ]]
