<a href="https://colab.research.google.com/github/ClaFlorez/travaux-avril-2024/blob/main/Exercise_Code1_Claudia.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
D'abord on importe toutes les librairies necesaires pour execute le programme
pour cet exercise on importe le tensorflow pour ammener toutes ses fontionnalités
et pas avoir besoin de écrire tout le chemin pour arriver a l'outil requis
'''

import tensorflow as tf  # Importation de la bibliothèque TensorFlow pour le calcul tensoriel

'''
configurer l'environement du systeme va nous aider entre autre à masquer les messages de warning et les messages
d'erreurs
'''

import os

'''
numpy on l'importe parce qu'on a beacoup de calcule psientifique à faire et on va
avoir besoin pour les calcules matriciel entre autes utilisé pour le traitement des données.
'''

import numpy as np  # Importation de la bibliothèque NumPy pour le calcul numérique

# en suite on va configurer  les messages d'erreur de TensorFlow dans le code suivante un niveau moderé sera utilisé
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'


In [2]:
# Définition d'un tenseur constant 'a' avec une valeur de 10
a = tf.constant(10)
# Affiche la valeur de 'a' à l'écran
print(f"a = {a}")

a = 10


In [5]:
#on crée une  contante appele B et va lui donner des valeurs fixes dans un tableau de 3 x 3
B = tf.constant([[1.,2.,3],[4,5,6],[7,8,9]])
print(f"B = {B}")

B = [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [6]:
# Affiche le contenu de la matrice 'B'
print(f"B = {B}")
# Affiche la forme (combien de files et colonnes) de la matrice 'B'
print(f"B.shape = {B.shape}")
# Affiche le type de données qui contiene la matrice 'B'
print(f"B.dtype = {B.dtype}")
# Affiche tous les éléments de la matrice 'B'
print(f"B[:,:] = {B[:,:]}")
# Affiche les lignes 2 et 3 de la matrice 'B' on va affichier de la file 1 à la fin
print(f"B[1:,:] = {B[1:,:]}")

B = [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
B.shape = (3, 3)
B.dtype = <dtype: 'float32'>
B[:,:] = [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
B[1:,:] = [[4. 5. 6.]
 [7. 8. 9.]]


In [9]:
# Ajoute 100 à chaque élément de la matrice 'B' et affiche le résultat
print(f"B+100 = {B+100.}")
'''
La matrice 'B' reste inchangée parce que le changement a été fait seulement à l'affichage de la matrice
et n'a pas été enregistré le changement dans un variable.
'''
print(f"B = {B}")
# Ajoute 100 à tous les éléments de la matrice 'B' (autre méthode) et affiche le résultat
print(f"B+100 = {tf.add(B,100.)}")
# La matrice 'B' reste inchangée parce un fois de plus le changements ont été faits à l'affichage
print(f"B = {B}")

B+100 = [[101. 102. 103.]
 [104. 105. 106.]
 [107. 108. 109.]]
B = [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
B+100 = [[101. 102. 103.]
 [104. 105. 106.]
 [107. 108. 109.]]
B = [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [10]:
# Création d'un tableau NumPy
''' dans un tableau unidimensionnel avec des données du même enregistré dans un variable
np_array_1
'''
np_array_1 = np.array([1., 2., 3., 4., 5., 6., 7., 8., 9., 10.])
# Affiche le tableau NumPy
print(np_array_1)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [11]:
# Conversion du tableau NumPy en tenseur TensorFlow
'''
les valeurs enregistrés dans np_array_1 on été déclarés comme un constante
tensorflow dans la variable tf_tensor
'''
tf_tensor = tf.constant(np_array_1)
# Affiche le tenseur TensorFlow
'''
quand on imprime la variable tf_tensor imprimé aussi les attributs de la variable
la forme - unidimensional - et le type d'elements - float64
'''
print(tf_tensor)

tf.Tensor([ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.], shape=(10,), dtype=float64)


In [13]:
# Conversion du tenseur TensorFlow en tableau NumPy
np_array_2 = tf_tensor.numpy()
# Affiche le tableau NumPy résultant de la conversion
'''
une autre facon de faire le changement
'''
print(np_array_2)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
